const GEN_MIN = 0;
const GEN_MAX = 127;

const DEFAULT_RANGE = [GEN_MIN, GEN_MAX];
const DEFAULT_STEP_INCREMENT = 1;
const DEFAULT_STEP_INCREMENT_SINE = 0.01;
const DEFAULT_FPS = 60;

export {
    GEN_MIN,
    GEN_MAX,
    DEFAULT_RANGE,
    DEFAULT_STEP_INCREMENT,
    DEFAULT_STEP_INCREMENT_SINE,
    DEFAULT_FPS
};
